#Pre-requisite: A Kubernetes cluster 
#Description: This Patternfile deploys OSM's demo Book store application in bookstore namespace
name: BookStore
services:
  7b24589e-2602-46d2-b82e-c0df9d3618d4:
    name: bookstore
    type: ServiceAccount.K8s
    namespace: bookstore
  57636a3b-adee-4baf-bb24-c73e9f01228c:
    name: bookstore
    type: Service.K8s
    namespace: bookstore
    labels:
      app: bookstore
    settings:
      spec:
        ports:
        - name: bookstore-port
          port: 14001
        selector:
          app: bookstore
  921797f2-3230-48a7-84a8-220820e108ec:
    name: bookstore
    type: Deployment.K8s
    namespace: bookstore
    settings:
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: bookstore
        template:
          metadata:
            labels:
              app: bookstore
          spec:
            containers:
            - args:
              - --port
              - "14001"
              command:
              - /bookstore
              env:
              - name: BOOKWAREHOUSE_NAMESPACE
                value: bookwarehouse
              - name: IDENTITY
                value: bookstore-v1
              image: openservicemesh/bookstore:latest-main
              imagePullPolicy: Always
              name: bookstore
              ports:
              - containerPort: 14001
                name: web
            nodeSelector:
              kubernetes.io/arch: amd64
              kubernetes.io/os: linux
            serviceAccountName: bookstore